### ISSUE TITLE
Problem with regex handling email verification

### ISSUE THREAD

**Issue by louismeuret** [LABIOQUIM/visualdynamics#55]
Hello, sorry to bother you
It seems that your mail verification doesn't take into account mails with several dots after the arobase, for example
student@etu.u-paris.fr doesn't work even though it's a valid address
Thank you
Louis

**Comment by ivopr** [comment]
Hey @Cyanure23012001, sorry for the slow response. and yes, it seems our regex wasn't taking into account dots, slashes and underscores on both sides of the email. I've pushed some changes on [this commit](https://github.com/LABIOQUIM/visualdynamics/commit/f6a12a8e4bf72ca5b11f2ee9a338e9ef44d62698). We're hoping to get that branch in production sometime between the next weeks.

**Comment by ivopr** [comment]
hey, @Cyanure23012001 Sorry about the delay, the version with this fix has been deployed. So, It should work now
